### ISSUE TITLE
swarming: Handle large pending queues better

### ISSUE THREAD

**Issue by vadimsht** [luci/luci-py#267]
Currently if the server has a large set of pending tasks for some specific set of dimensions, it slows down every /bot/poll handler: yield_next_available_task_to_dispatch [1] sifts through a lot of tasks until it find a suitable one.

For example, if there's 1000 tasks with "{os: Linux, pool: CT}" dimensions, and the polling bot is "{os:Linux, pool: default}", it will visit each Skia task and skip it, since it doesn't match the dimensions.

One proposal to make things better:
1. Promote "pool" to a magical dimension that is expected to be specified in all tasks and advertised by all bots (I think it already de facto is).
2. Put value of 'pool' into indexable property of TaskToRun entity.
3. In yield_next_available_task_to_dispatch when querying for TaskToRun entities, do datastore filtering on the 'pool' property.

Advantages: now tasks in some pool can screw up only this pool, not other pools :)
Disadvantages: requires new composite index, it may slow down task submissions. 

[1] https://github.com/luci/luci-py/blob/1f28f8b/appengine/swarming/server/task_to_run.py#L292

**Comment by rmistry** [comment]
![happy](https://cloud.githubusercontent.com/assets/5244662/16487342/4988ca90-3e98-11e6-8ed2-4a28a1ee26f3.jpg)

**Comment by mithro** [comment]
A totally different way to solve this problem is to have each "dimension set" be its own queue. A bot then first checks the most specific queue for tasks, if it doesn't find any it then looks at a less specific queues "walking upwards" until it hits a very generic queue.

This had a couple of nice side effects;
 * Bots are not affected by tasks they can never service (as they never even visit the queue the task is in).
 * Very picky tasks will end up being put on the bots which can satisfy them first, while the less picky tasks will tend towards the more generic bots. This is a better load sharing strategy, as you shouldn't end up with a picky task being unserviceable because the only bot with the correct attributes is currently servicing a task which could be done by a more generic one.

On another note, after chatting with some AppEngine task queue experts (who worked on it before it got defragged out of Sydney), it sounds like it would be actually pretty simple to build such a system on top of the built in task queue system. This would give you a huge amount of advantages like better monitoring, tools for flushing and querying, etc.

**Comment by vadimsht** [comment]
There are thousands of possible "dimension sets". We even have an artificial limit of 16384 (and it was being hit on some android bots) https://github.com/luci/luci-py/blob/master/appengine/swarming/server/task_to_run.py#L41 

Checking them one by one (even if starting from leaf nodes) will probably make /poll do large large amount of datastore queries even for case when the server is not loaded (no pending tasks).

(Not that "OR" in datastore query is just a sugar for multiple parallel RPCs).

So I think we still need to introduce some logic for dividing search space into "most promising candidates" and "everything else".

**Comment by mithro** [comment]
How many possible "dimension sets" are in use by submitted tasks at one time? I would be surprised if it was more than a couple of hundred?

Maybe you could lazily create queues as you see new tasks which have a set of dimensions? Then just have something which collects a summary of how many items are in each queue (which runs every second). The system just then needs to do a single query for the summary information...

**Comment by maruel** [comment]
_[Back from vacation]_

I thought I had filed a formal issue for this AI but I had forgot! Thanks @vadimsht!

My plan is closer to what @mithro described; there's no need to special case `pool`. There's already an hashing function for a _dimension set_.

@vadimsht noted that there is an issue about the 16k limit, as the current way we need to evaluate all valid hashes. In practice, this is because the poller doesn't know the ones _currently in use_ with the current scheme. This issue is about fixing that.

With multiple queues, one per dimensions set hash, we actually _know_ which dimensions sets are in use, and this is significantly bounded; as @mithro speculated, there's likely less than 100 different sets used _at any given time_, the worst case is when a task is run per bot id. Note that we only care about the dimensions sets with pending tasks, not all dimension sets that ever _had_ a pending task.

This means the bot can precalculate and cache which hashes are on or off, cache these int32 inside BotInfo.

The list of hashes in use can be stored in memcache.

This results that there is no need to impose the 16k limit anymore, which is damn cool.

This is true as @vadimsht say that this results in multiple queries. The truth is that in practice, the number of queries run is actually pretty small. It is the number of different sets a bot can run and it is generally rather small, in the range of [0, 5] or so. There will be work needed on this side too as the performance characteristic will be bounded by the number of different active queues a bot can process simultaneously.

**Comment by maruel** [comment]
Fixed.
