### ISSUE TITLE
Idea: quarantine Swarming bots due to failure rate

### ISSUE THREAD

**Issue by erock2112** [luci/luci-py#277]
eg. If a given bot has failed consistently for the past 5 tasks, there's probably something wrong with it, so quarantine it.

**Comment by kenrussell** [comment]
+1, a meta-monitor like this would be very useful.

The physical bots in the Swarming pool occasionally experience hardware failures that result in certain tests reliably failing.

Scanning recent jobs (~50?) and seeing if all tests of a certain kind were failing (and weren't all CL tryjobs sent by one specific user), and auto-quarantining the machine if so and sending an alert, would be very helpful. See http://crbug.com/638727 .

**Comment by maruel** [comment]
1. Doing the N last task is relatively easy.
1. Doing it with non deterministic analysis is much harder, as Swarming doesn't have enough information to make a good decision.

I prefer to keep this issue focused on the first.

For the second, an option is to run a cron job (e.g. via SoM) to query and do domain specific analysis (e.g. try job vs CI).

**Comment by kenrussell** [comment]
Nothing is non-deterministic about the analysis I'm suggesting. Looking more closely, such as this shard:
https://chromium-swarm.appspot.com/task?id=35aa5576b5772510

from "webgl2_conformance_tests on NVIDIA GPU on Mac Retina (with patch)" from this tryjob:
https://build.chromium.org/p/tryserver.chromium.mac/builders/mac_optional_gpu_tests_rel/builds/9276

All of the needed information is available in Swarming:
 - The job's name can be chopped up and the unchanging parts used for matching.
 - Tryjobs have an associated user (which I'd forgotten).

In particular, it isn't necessary to go back to codereview.chromium.org or PolyGerrit, which I'd forgotten.

If there are reliable failures of the same job name on a given machine -- ignoring duplicates coming all from the same user -- that would be a strong signal that something's wrong with the machine.

(The possibility of false positives due to breakage of the tree, perhaps due to reverts, is a problem. It'd also be a problem for doing entirely local analysis of just the last N jobs.)

**Comment by maruel** [comment]
Migrated to https://bugs.chromium.org/p/chromium/issues/detail?id=757932
